### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by adamhuang1416** [PurdueElectricRacing/LapSim#11]
**Describe the bug**
Hi, I'm from Taiwan NTHU. First of all, I want to my appreciation for you to open source this code, I can;t thank you guys enough!!
So the problem is that when we plug in our parameters of our racecar in MATLAB, one of the array should have the size 36x1 but instead it has 36x36(this array maybe is responsible for the velocity and there is a lot of 0 in the columns 1~35 ) and it caused the loop to run forever and there is no result. Someone told me that the bug is in one of the header files and it's something to do with Data Structures?(I'm not from CS, so I don't know) 
Can you please fix the problem?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by DMoore12** [comment]
Hi Adam, thanks for finding this. Could you post a picture of the output from the simulator/errors? We put this project down some time ago, so it's likely got an error somewhere. Our organization is undergoing final examinations this week, but hopefully we can take a look at it soon and get it patched up
